# Generated by Django 5.1 on 2025-06-28 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="enrolled_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrolled_students",
                to="content.class",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="accounts.school",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"role": "Student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="assigned_classes",
            field=models.ManyToManyField(
                blank=True, related_name="teachers_assigned", to="content.class"
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="accounts.school",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="subject_expertise",
            field=models.ManyToManyField(
                blank=True, related_name="expert_teachers", to="content.subject"
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"role": "Teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="parentstudentlink",
            unique_together={("parent", "student")},
        ),
    ]
