# Generated by Django 5.1.4 on 2025-06-28 10:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="face_encoding",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_school_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Teacher", "Teacher"),
                    ("Parent", "Parent"),
                    ("Admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.school",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="parentprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="parentprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="parentprofile",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="parentprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pics/parents/"
            ),
        ),
        migrations.AlterField(
            model_name="parentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="parentstudentlink",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="parentstudentlink",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="school",
            name="admin_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="administered_school",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="license_number",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="school",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="school",
            name="principal_contact_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="school",
            name="principal_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="school",
            name="principal_full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="school",
            name="school_id_code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="admission_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="blood_group",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="enrolled_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="content.class",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="father_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="favorite_sports",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="hobbies",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="mother_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="nickname",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="parent_email_for_linking",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="parent_mobile_for_linking",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="parent_occupation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="preferred_language",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pics/students/"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.school",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="assigned_classes",
            field=models.ManyToManyField(blank=True, to="content.class"),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pics/teachers/"
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.school",
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="subject_expertise",
            field=models.ManyToManyField(blank=True, to="content.subject"),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
